name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build site
        run: |
          npm install 
          npm run build 

      - name: Deploy to GitHub Pages
        uses: uladaharanina/Portfolio@releases/v1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build # Or the folder where your built site resides
